<?php
return [
 'site'=>['name'=>'Realms Bans','title'=>'{page} - Realms Bans','description'=>'Riwayat hukuman Minecraft publik dan dapat dicari untuk RealmsNetwork'],
 'nav'=>['home'=>'Beranda','bans'=>'Ban','mutes'=>'Mute','warnings'=>'Peringatan','kicks'=>'Kick','statistics'=>'Statistik','language'=>'Bahasa','theme'=>'Tema','admin'=>'Admin','protest'=>'Ajukan banding ban'],
 'home'=>['welcome'=>'Hukuman Server','description'=>'Cari pemain dan lihat aktivitas moderasi terbaru','recent_activity'=>'Aktivitas terbaru','recent_bans'=>'Ban terbaru','recent_mutes'=>'Mute terbaru','no_recent_bans'=>'Tidak ada ban terbaru','no_recent_mutes'=>'Tidak ada mute terbaru','view_all_bans'=>'Lihat semua ban','view_all_mutes'=>'Lihat semua mute'],
 'search'=>['title'=>'Cari pemain','placeholder'=>'Masukkan nama pemain atau UUID...','help'=>'Anda dapat mencari berdasarkan nama pemain atau UUID lengkap','button'=>'Cari','no_results'=>'Tidak ada hukuman untuk pemain ini','error'=>'Terjadi kesalahan pencarian','network_error'=>'Terjadi kesalahan jaringan. Silakan coba lagi.'],
 'stats'=>['title'=>'Statistik Server','active_bans'=>'Ban aktif','active_mutes'=>'Mute aktif','total_warnings'=>'Total peringatan','total_kicks'=>'Total kick','total_of'=>'dari','all_time'=>'sepanjang waktu','most_banned_players'=>'Pemain paling sering diban','most_active_staff'=>'Staff paling aktif','top_ban_reasons'=>'Alasan ban paling umum','recent_activity_overview'=>'Ringkasan aktivitas terbaru','activity_by_day'=>'Aktivitas per hari','cache_cleared'=>'Cache statistik dibersihkan','cache_clear_failed'=>'Gagal membersihkan cache statistik','clear_cache'=>'Bersihkan cache','last_24h'=>'24 jam terakhir','last_7d'=>'7 hari terakhir','last_30d'=>'30 hari terakhir'],
 'table'=>['player'=>'Pemain','reason'=>'Alasan','staff'=>'Staff','date'=>'Tanggal','expires'=>'Berakhir','status'=>'Status','actions'=>'Aksi','type'=>'Tipe','view'=>'Lihat','total'=>'Total','active'=>'Aktif','last_ban'=>'Ban terakhir','last_action'=>'Aksi terakhir','server'=>'Server'],
 'status'=>['active'=>'Aktif','inactive'=>'Tidak aktif','expired'=>'Kedaluwarsa','removed'=>'Dihapus','completed'=>'Selesai','removed_by'=>'Dihapus oleh'],
 'punishment'=>['permanent'=>'Permanen','expired'=>'Kedaluwarsa'],
 'punishments'=>['no_data'=>'Tidak ada hukuman ditemukan','no_data_desc'=>'Saat ini tidak ada hukuman untuk ditampilkan'],
 'detail'=>['duration'=>'Durasi','time_left'=>'Sisa waktu','progress'=>'Progres','removed_by'=>'Dihapus oleh','removed_date'=>'Tanggal dihapus','flags'=>'Flag','other_punishments'=>'Hukuman lain'],
 'pagination'=>['label'=>'Navigasi halaman','previous'=>'Sebelumnya','next'=>'Berikutnya','page_info'=>'Halaman {current} dari {total}'],
 'footer'=>['rights'=>'Hak cipta dilindungi.','powered_by'=>'Dibuat dengan','license'=>'Dilisensikan di bawah'],
 'error'=>['not_found'=>'Halaman tidak ditemukan','server_error'=>'Terjadi kesalahan server','invalid_request'=>'Permintaan tidak valid','punishment_not_found'=>'Hukuman yang diminta tidak ditemukan.','loading_failed'=>'Gagal memuat detail hukuman.'],
 'protest'=>['title'=>'Banding Ban','description'=>'Jika Anda yakin ban diberikan secara keliru, Anda dapat meminta peninjauan.','how_to_title'=>'Cara mengajukan banding ban','how_to_subtitle'=>'Ikuti langkah berikut untuk meminta unban:','step1_title'=>'1. Siapkan informasi','step1_desc'=>'Siapkan:','step1_items'=>['Nama Minecraft Anda','Tanggal dan waktu ban','Alasan ban','Bukti pendukung'],'step2_title'=>'2. Metode kontak','step2_desc'=>'Kirim banding melalui salah satu metode berikut:','discord_title'=>'Discord (disarankan)','discord_desc'=>'Bergabung ke Discord dan buat tiket banding ban','discord_button'=>'Buka Discord','email_title'=>'Email','email_desc'=>'Kirim banding ke:','forum_title'=>'Forum','forum_desc'=>'Buat posting di bagian banding forum.','forum_button'=>'Buka forum','step3_title'=>'3. Yang harus disertakan','step3_desc'=>'Sertakan nama, kejadian, alasan banding, dan perubahan yang Anda inginkan.','step3_items'=>['Nama Minecraft','Tanggal dan waktu perkiraan','Staff yang memberi ban jika diketahui','Penjelasan rinci','Screenshot atau bukti','Cerita yang jujur'],'step4_title'=>'4. Tunggu peninjauan','step4_desc'=>'Tim staff akan meninjau banding Anda. Jangan mengirim banyak banding untuk ban yang sama.','guidelines_title'=>'Panduan penting','guidelines_items'=>['Jujur dan hormat','Jangan berikan informasi palsu','Jangan spam','Terima keputusan akhir staff','Upaya menghindari ban dapat berujung ban permanen'],'warning_title'=>'Peringatan','warning_desc'=>'Informasi palsu atau upaya menipu staff dapat menyebabkan banding ditolak dan hukuman tambahan.','form_not_available'=>'Pengiriman banding langsung saat ini tidak tersedia. Gunakan salah satu metode kontak di atas.']
];