<?php
return [
 'site'=>['name'=>'Realms Bans','title'=>'{page} - Realms Bans','description'=>'Openbare, doorzoekbare geschiedenis van Minecraft-straffen op RealmsNetwork'],
 'nav'=>['home'=>'Home','bans'=>'Bans','mutes'=>'Mutes','warnings'=>'Waarschuwingen','kicks'=>'Kicks','statistics'=>'Statistieken','language'=>'Taal','theme'=>'Thema','admin'=>'Beheer','protest'=>'Ban aanvechten'],
 'home'=>['welcome'=>'Serverstraffen','description'=>'Zoek spelers op en bekijk recente moderatieactiviteiten','recent_activity'=>'Recente activiteit','recent_bans'=>'Recente bans','recent_mutes'=>'Recente mutes','no_recent_bans'=>'Geen recente bans gevonden','no_recent_mutes'=>'Geen recente mutes gevonden','view_all_bans'=>'Alle bans bekijken','view_all_mutes'=>'Alle mutes bekijken'],
 'search'=>['title'=>'Spelers zoeken','placeholder'=>'Voer spelernaam of UUID in...','help'=>'Je kunt zoeken op spelernaam of volledige UUID','button'=>'Zoeken','no_results'=>'Geen straffen voor deze speler gevonden','error'=>'Er is een zoekfout opgetreden','network_error'=>'Netwerkfout. Probeer het opnieuw.'],
 'stats'=>['title'=>'Serverstatistieken','active_bans'=>'Actieve bans','active_mutes'=>'Actieve mutes','total_warnings'=>'Totaal waarschuwingen','total_kicks'=>'Totaal kicks','total_of'=>'van','all_time'=>'altijd','most_banned_players'=>'Meest gebande spelers','most_active_staff'=>'Actiefste staff','top_ban_reasons'=>'Meest voorkomende banredenen','recent_activity_overview'=>'Overzicht recente activiteit','activity_by_day'=>'Activiteit per dag','cache_cleared'=>'Statistische cache gewist','cache_clear_failed'=>'Statistische cache kon niet worden gewist','clear_cache'=>'Cache wissen','last_24h'=>'Laatste 24 uur','last_7d'=>'Laatste 7 dagen','last_30d'=>'Laatste 30 dagen'],
 'table'=>['player'=>'Speler','reason'=>'Reden','staff'=>'Staff','date'=>'Datum','expires'=>'Verloopt','status'=>'Status','actions'=>'Acties','type'=>'Type','view'=>'Bekijken','total'=>'Totaal','active'=>'Actief','last_ban'=>'Laatste ban','last_action'=>'Laatste actie','server'=>'Server'],
 'status'=>['active'=>'Actief','inactive'=>'Inactief','expired'=>'Verlopen','removed'=>'Verwijderd','completed'=>'Voltooid','removed_by'=>'Verwijderd door'],
 'punishment'=>['permanent'=>'Permanent','expired'=>'Verlopen'],
 'punishments'=>['no_data'=>'Geen straffen gevonden','no_data_desc'=>'Er zijn momenteel geen straffen om te tonen'],
 'detail'=>['duration'=>'Duur','time_left'=>'Resterende tijd','progress'=>'Voortgang','removed_by'=>'Verwijderd door','removed_date'=>'Verwijderdatum','flags'=>'Vlaggen','other_punishments'=>'Andere straffen'],
 'pagination'=>['label'=>'Paginanavigatie','previous'=>'Vorige','next'=>'Volgende','page_info'=>'Pagina {current} van {total}'],
 'footer'=>['rights'=>'Alle rechten voorbehouden.','powered_by'=>'Aangedreven door','license'=>'Gelicenseerd onder'],
 'error'=>['not_found'=>'Pagina niet gevonden','server_error'=>'Er is een serverfout opgetreden','invalid_request'=>'Ongeldig verzoek','punishment_not_found'=>'De opgevraagde straf kon niet worden gevonden.','loading_failed'=>'Laden van strafdetails mislukt.'],
 'protest'=>['title'=>'Ban aanvechten','description'=>'Denk je dat je ban onterecht is uitgegeven? Vraag dan een beoordeling aan.','how_to_title'=>'Een ban aanvechten','how_to_subtitle'=>'Volg deze stappen om een unban aan te vragen:','step1_title'=>'1. Verzamel je gegevens','step1_desc'=>'Zorg dat je dit bij de hand hebt:','step1_items'=>['Je Minecraft-gebruikersnaam','Datum en tijd van je ban','De opgegeven banreden','Bewijs dat je zaak ondersteunt'],'step2_title'=>'2. Contactmethoden','step2_desc'=>'Je kunt je protest via een van de volgende methoden indienen:','discord_title'=>'Discord (aanbevolen)','discord_desc'=>'Ga naar onze Discord en maak een ticket in het ban-protestkanaal','discord_button'=>'Discord openen','email_title'=>'E-mail','email_desc'=>'Stuur je protest naar:','forum_title'=>'Forum','forum_desc'=>'Maak een bericht in de sectie Ban Protests van ons forum.','forum_button'=>'Forum openen','step3_title'=>'3. Wat je moet vermelden','step3_desc'=>'Vermeld je naam, wat er is gebeurd, waarom je protesteert en wat je wilt veranderen.','step3_items'=>['Je Minecraft-gebruikersnaam','Datum en ongeveer tijdstip van de ban','De stafflid die de ban uitgaf, indien bekend','Een duidelijke uitleg waarom de ban oneerlijk is','Screenshots of ander bewijs','Een eerlijke beschrijving van wat er is gebeurd'],'step4_title'=>'4. Wacht op beoordeling','step4_desc'=>'Ons staffteam beoordeelt je protest. Stuur geen meerdere verzoeken voor dezelfde ban.','guidelines_title'=>'Belangrijke richtlijnen','guidelines_items'=>['Wees eerlijk en respectvol','Geef geen valse informatie','Spam geen protesten','Accepteer de eindbeslissing van het staffteam','Ban-ontwijking kan tot een permanente ban leiden'],'warning_title'=>'Waarschuwing','warning_desc'=>'Valse informatie of misleiding kan leiden tot afwijzing van je protest en extra straf.','form_not_available'=>'Direct protest indienen is momenteel niet beschikbaar. Gebruik een van de bovenstaande contactmethoden.']
];