<?php
return [
 'site'=>['name'=>'Realms Bans','title'=>'{page} - Realms Bans','description'=>'Offentlig og søkbar Minecraft-straffhistorikk for RealmsNetwork'],
 'nav'=>['home'=>'Hjem','bans'=>'Bans','mutes'=>'Mutes','warnings'=>'Advarsler','kicks'=>'Kicks','statistics'=>'Statistikk','language'=>'Språk','theme'=>'Tema','admin'=>'Admin','protest'=>'Klage på ban'],
 'home'=>['welcome'=>'Serverstraff','description'=>'Søk etter spillere og se nylig modereringsaktivitet','recent_activity'=>'Nylig aktivitet','recent_bans'=>'Nylige bans','recent_mutes'=>'Nylige mutes','no_recent_bans'=>'Ingen nylige bans funnet','no_recent_mutes'=>'Ingen nylige mutes funnet','view_all_bans'=>'Vis alle bans','view_all_mutes'=>'Vis alle mutes'],
 'search'=>['title'=>'Spillersøk','placeholder'=>'Skriv spillernavn eller UUID...','help'=>'Du kan søke med spillernavn eller full UUID','button'=>'Søk','no_results'=>'Ingen straff funnet for denne spilleren','error'=>'Det oppstod en søkefeil','network_error'=>'Nettverksfeil. Prøv igjen.'],
 'stats'=>['title'=>'Serverstatistikk','active_bans'=>'Aktive bans','active_mutes'=>'Aktive mutes','total_warnings'=>'Totale advarsler','total_kicks'=>'Totale kicks','total_of'=>'av','all_time'=>'totalt','most_banned_players'=>'Mest bannede spillere','most_active_staff'=>'Mest aktive staff','top_ban_reasons'=>'Vanligste banårsaker','recent_activity_overview'=>'Oversikt over nylig aktivitet','activity_by_day'=>'Aktivitet per dag','cache_cleared'=>'Statistikkbuffer tømt','cache_clear_failed'=>'Kunne ikke tømme statistikkbufferen','clear_cache'=>'Tøm buffer','last_24h'=>'Siste 24 timer','last_7d'=>'Siste 7 dager','last_30d'=>'Siste 30 dager'],
 'table'=>['player'=>'Spiller','reason'=>'Årsak','staff'=>'Staff','date'=>'Dato','expires'=>'Utløper','status'=>'Status','actions'=>'Handlinger','type'=>'Type','view'=>'Vis','total'=>'Totalt','active'=>'Aktiv','last_ban'=>'Siste ban','last_action'=>'Siste handling','server'=>'Server'],
 'status'=>['active'=>'Aktiv','inactive'=>'Inaktiv','expired'=>'Utløpt','removed'=>'Fjernet','completed'=>'Fullført','removed_by'=>'Fjernet av'],
 'punishment'=>['permanent'=>'Permanent','expired'=>'Utløpt'],
 'punishments'=>['no_data'=>'Ingen straffer funnet','no_data_desc'=>'Det finnes ingen straffer å vise akkurat nå'],
 'detail'=>['duration'=>'Varighet','time_left'=>'Gjenstående tid','progress'=>'Fremdrift','removed_by'=>'Fjernet av','removed_date'=>'Fjerningsdato','flags'=>'Flagg','other_punishments'=>'Andre straffer'],
 'pagination'=>['label'=>'Sidenavigasjon','previous'=>'Forrige','next'=>'Neste','page_info'=>'Side {current} av {total}'],
 'footer'=>['rights'=>'Alle rettigheter forbeholdt.','powered_by'=>'Drevet av','license'=>'Lisensiert under'],
 'error'=>['not_found'=>'Siden ble ikke funnet','server_error'=>'En serverfeil oppstod','invalid_request'=>'Ugyldig forespørsel','punishment_not_found'=>'Den forespurte straffen ble ikke funnet.','loading_failed'=>'Kunne ikke laste straffedetaljer.'],
 'protest'=>['title'=>'Klage på ban','description'=>'Mener du at banen ble gitt ved en feil, kan du be om en gjennomgang.','how_to_title'=>'Slik klager du på en ban','how_to_subtitle'=>'Følg disse trinnene for å be om unban:','step1_title'=>'1. Samle informasjon','step1_desc'=>'Ha dette klart:','step1_items'=>['Minecraft-brukernavn','Dato og tidspunkt for ban','Oppgitt grunn','Bevis som støtter saken'],'step2_title'=>'2. Kontaktmetoder','step2_desc'=>'Send klagen via en av metodene under:','discord_title'=>'Discord (anbefalt)','discord_desc'=>'Bli med på Discord og opprett en ticket for ban-klage','discord_button'=>'Åpne Discord','email_title'=>'E-post','email_desc'=>'Send klagen til:','forum_title'=>'Forum','forum_desc'=>'Opprett et innlegg i forumets klageseksjon.','forum_button'=>'Åpne forum','step3_title'=>'3. Hva du bør ta med','step3_desc'=>'Ta med navn, hva som skjedde, hvorfor du klager og hva du vil endre.','step3_items'=>['Minecraft-brukernavn','Dato og omtrentlig tidspunkt','Staff som ga ban, hvis kjent','Detaljert forklaring','Skjermbilder eller bevis','Ærlig beskrivelse av hendelsen'],'step4_title'=>'4. Vent på gjennomgang','step4_desc'=>'Staffteamet gjennomgår klagen. Ikke send flere klager for samme ban.','guidelines_title'=>'Viktige retningslinjer','guidelines_items'=>['Vær ærlig og respektfull','Ikke gi falsk informasjon','Ikke spam','Godta teamets endelige avgjørelse','Ban-omgåelse kan føre til permanent ban'],'warning_title'=>'Advarsel','warning_desc'=>'Falsk informasjon eller forsøk på å lure staff kan føre til avslag og ekstra straff.','form_not_available'=>'Direkte innsending av klager er ikke tilgjengelig akkurat nå. Bruk en kontaktmetode over.']
];