<?php
return [
 'site'=>['name'=>'Realms Bans','title'=>'{page} - Realms Bans','description'=>'Histórico público e pesquisável de punições do Minecraft na RealmsNetwork'],
 'nav'=>['home'=>'Início','bans'=>'Bans','mutes'=>'Mutes','warnings'=>'Advertências','kicks'=>'Kicks','statistics'=>'Estatísticas','language'=>'Idioma','theme'=>'Tema','admin'=>'Admin','protest'=>'Recorrer da ban'],
 'home'=>['welcome'=>'Punições do servidor','description'=>'Pesquise jogadores e veja as atividades recentes de moderação','recent_activity'=>'Atividade recente','recent_bans'=>'Bans recentes','recent_mutes'=>'Mutes recentes','no_recent_bans'=>'Nenhuma ban recente encontrada','no_recent_mutes'=>'Nenhuma mute recente encontrada','view_all_bans'=>'Ver todas as bans','view_all_mutes'=>'Ver todas as mutes'],
 'search'=>['title'=>'Buscar jogador','placeholder'=>'Digite o nome do jogador ou UUID...','help'=>'Você pode buscar pelo nome do jogador ou UUID completo','button'=>'Buscar','no_results'=>'Nenhuma punição encontrada para este jogador','error'=>'Ocorreu um erro na busca','network_error'=>'Erro de rede. Tente novamente.'],
 'stats'=>['title'=>'Estatísticas do servidor','active_bans'=>'Bans ativas','active_mutes'=>'Mutes ativas','total_warnings'=>'Total de advertências','total_kicks'=>'Total de kicks','total_of'=>'de','all_time'=>'no total','most_banned_players'=>'Jogadores mais banidos','most_active_staff'=>'Staff mais ativo','top_ban_reasons'=>'Motivos de ban mais comuns','recent_activity_overview'=>'Resumo da atividade recente','activity_by_day'=>'Atividade por dia','cache_cleared'=>'Cache de estatísticas limpo','cache_clear_failed'=>'Não foi possível limpar o cache','clear_cache'=>'Limpar cache','last_24h'=>'Últimas 24 horas','last_7d'=>'Últimos 7 dias','last_30d'=>'Últimos 30 dias'],
 'table'=>['player'=>'Jogador','reason'=>'Motivo','staff'=>'Staff','date'=>'Data','expires'=>'Expira','status'=>'Status','actions'=>'Ações','type'=>'Tipo','view'=>'Ver','total'=>'Total','active'=>'Ativa','last_ban'=>'Última ban','last_action'=>'Última ação','server'=>'Servidor'],
 'status'=>['active'=>'Ativa','inactive'=>'Inativa','expired'=>'Expirada','removed'=>'Removida','completed'=>'Concluída','removed_by'=>'Removida por'],
 'punishment'=>['permanent'=>'Permanente','expired'=>'Expirada'],
 'punishments'=>['no_data'=>'Nenhuma punição encontrada','no_data_desc'=>'Não há punições para exibir no momento'],
 'detail'=>['duration'=>'Duração','time_left'=>'Tempo restante','progress'=>'Progresso','removed_by'=>'Removida por','removed_date'=>'Data de remoção','flags'=>'Flags','other_punishments'=>'Outras punições'],
 'pagination'=>['label'=>'Navegação de páginas','previous'=>'Anterior','next'=>'Próxima','page_info'=>'Página {current} de {total}'],
 'footer'=>['rights'=>'Todos os direitos reservados.','powered_by'=>'Desenvolvido por','license'=>'Licenciado sob'],
 'error'=>['not_found'=>'Página não encontrada','server_error'=>'Ocorreu um erro no servidor','invalid_request'=>'Solicitação inválida','punishment_not_found'=>'A punição solicitada não foi encontrada.','loading_failed'=>'Não foi possível carregar os detalhes da punição.'],
 'protest'=>['title'=>'Recurso de ban','description'=>'Acredita que sua ban foi aplicada por engano? Você pode solicitar uma revisão.','how_to_title'=>'Como recorrer de uma ban','how_to_subtitle'=>'Siga estas etapas para solicitar uma revisão:','step1_title'=>'1. Reúna suas informações','step1_desc'=>'Tenha estas informações prontas:','step1_items'=>['Seu nome do Minecraft','Data e hora da ban','Motivo informado','Provas que apoiem seu caso'],'step2_title'=>'2. Métodos de contato','step2_desc'=>'Envie seu recurso por um dos seguintes métodos:','discord_title'=>'Discord (recomendado)','discord_desc'=>'Entre no nosso Discord e abra um ticket no canal de recursos','discord_button'=>'Abrir Discord','email_title'=>'E-mail','email_desc'=>'Envie seu recurso para:','forum_title'=>'Fórum','forum_desc'=>'Crie uma publicação na seção de recursos do fórum.','forum_button'=>'Abrir fórum','step3_title'=>'3. O que incluir','step3_desc'=>'Informe seu nome, o que aconteceu, por que está recorrendo e o que deseja que seja alterado.','step3_items'=>['Seu nome do Minecraft','Data e horário aproximado da ban','Staff que aplicou a ban, se souber','Explicação detalhada do motivo do recurso','Screenshots ou outras provas','Relato honesto do ocorrido'],'step4_title'=>'4. Aguarde a análise','step4_desc'=>'Nossa equipe analisará seu recurso. Não envie vários pedidos para a mesma ban.','guidelines_title'=>'Regras importantes','guidelines_items'=>['Seja honesto e respeitoso','Não forneça informações falsas','Não envie spam','Aceite a decisão final da equipe','Evasão de ban pode resultar em ban permanente'],'warning_title'=>'Aviso','warning_desc'=>'Informações falsas ou tentativa de enganar a equipe podem causar a rejeição do recurso e punições adicionais.','form_not_available'=>'O envio direto de recursos não está disponível no momento. Use um dos métodos de contato acima.']
];