<?php
return [
 'site'=>['name'=>'Realms Bans','title'=>'{page} - Realms Bans','description'=>'Offentlig och sökbar Minecraft-straffhistorik för RealmsNetwork'],
 'nav'=>['home'=>'Hem','bans'=>'Avstängningar','mutes'=>'Mutes','warnings'=>'Varningar','kicks'=>'Kicks','statistics'=>'Statistik','language'=>'Språk','theme'=>'Tema','admin'=>'Admin','protest'=>'Överklaga ban'],
 'home'=>['welcome'=>'Serverstraff','description'=>'Sök efter spelare och se senaste modereringsaktiviteten','recent_activity'=>'Senaste aktivitet','recent_bans'=>'Senaste bans','recent_mutes'=>'Senaste mutes','no_recent_bans'=>'Inga nya bans hittades','no_recent_mutes'=>'Inga nya mutes hittades','view_all_bans'=>'Visa alla bans','view_all_mutes'=>'Visa alla mutes'],
 'search'=>['title'=>'Spelarsökning','placeholder'=>'Ange spelarnamn eller UUID...','help'=>'Du kan söka med spelarnamn eller fullständig UUID','button'=>'Sök','no_results'=>'Inga straff hittades för spelaren','error'=>'Ett sökfel uppstod','network_error'=>'Nätverksfel. Försök igen.'],
 'stats'=>['title'=>'Serverstatistik','active_bans'=>'Aktiva bans','active_mutes'=>'Aktiva mutes','total_warnings'=>'Totala varningar','total_kicks'=>'Totala kicks','total_of'=>'av','all_time'=>'totalt','most_banned_players'=>'Mest bannade spelare','most_active_staff'=>'Aktivaste staff','top_ban_reasons'=>'Vanligaste banorsakerna','recent_activity_overview'=>'Översikt över senaste aktivitet','activity_by_day'=>'Aktivitet per dag','cache_cleared'=>'Statistikcache rensad','cache_clear_failed'=>'Kunde inte rensa statistikcachen','clear_cache'=>'Rensa cache','last_24h'=>'Senaste 24 timmarna','last_7d'=>'Senaste 7 dagarna','last_30d'=>'Senaste 30 dagarna'],
 'table'=>['player'=>'Spelare','reason'=>'Orsak','staff'=>'Staff','date'=>'Datum','expires'=>'Går ut','status'=>'Status','actions'=>'Åtgärder','type'=>'Typ','view'=>'Visa','total'=>'Totalt','active'=>'Aktiv','last_ban'=>'Senaste ban','last_action'=>'Senaste åtgärd','server'=>'Server'],
 'status'=>['active'=>'Aktiv','inactive'=>'Inaktiv','expired'=>'Utgången','removed'=>'Borttagen','completed'=>'Slutförd','removed_by'=>'Borttagen av'],
 'punishment'=>['permanent'=>'Permanent','expired'=>'Utgången'],
 'punishments'=>['no_data'=>'Inga straff hittades','no_data_desc'=>'Det finns inga straff att visa just nu'],
 'detail'=>['duration'=>'Varaktighet','time_left'=>'Återstående tid','progress'=>'Förlopp','removed_by'=>'Borttagen av','removed_date'=>'Borttagen datum','flags'=>'Flaggor','other_punishments'=>'Andra straff'],
 'pagination'=>['label'=>'Sidnavigering','previous'=>'Föregående','next'=>'Nästa','page_info'=>'Sida {current} av {total}'],
 'footer'=>['rights'=>'Med ensamrätt.','powered_by'=>'Drivs av','license'=>'Licensierad under'],
 'error'=>['not_found'=>'Sidan hittades inte','server_error'=>'Ett serverfel uppstod','invalid_request'=>'Ogiltig begäran','punishment_not_found'=>'Det begärda straffet hittades inte.','loading_failed'=>'Kunde inte läsa in straffdetaljer.'],
 'protest'=>['title'=>'Överklaga ban','description'=>'Om du anser att din ban utfärdades av misstag kan du begära granskning.','how_to_title'=>'Så överklagar du en ban','how_to_subtitle'=>'Följ dessa steg för att begära unban:','step1_title'=>'1. Samla information','step1_desc'=>'Ha detta redo:','step1_items'=>['Ditt Minecraft-namn','Datum och tid för din ban','Angiven orsak','Bevis som stöder din sak'],'step2_title'=>'2. Kontaktmetoder','step2_desc'=>'Skicka överklagandet via någon av följande metoder:','discord_title'=>'Discord (rekommenderas)','discord_desc'=>'Gå med i vår Discord och skapa en ticket för banöverklagande','discord_button'=>'Öppna Discord','email_title'=>'E-post','email_desc'=>'Skicka ditt överklagande till:','forum_title'=>'Forum','forum_desc'=>'Skapa ett inlägg i forumets överklagandesektion.','forum_button'=>'Öppna forum','step3_title'=>'3. Vad som ska ingå','step3_desc'=>'Ta med namn, vad som hände, varför du överklagar och vad du vill ändra.','step3_items'=>['Minecraft-namn','Datum och ungefärlig tid','Staff som utfärdade banen om känt','Detaljerad förklaring','Skärmdumpar eller bevis','Ärlig beskrivning av händelsen'],'step4_title'=>'4. Vänta på granskning','step4_desc'=>'Staffteamet granskar överklagandet. Skicka inte flera överklaganden för samma ban.','guidelines_title'=>'Viktiga riktlinjer','guidelines_items'=>['Var ärlig och respektfull','Lämna inte falsk information','Spamma inte','Acceptera teamets slutliga beslut','Ban-kringgående kan leda till permanent ban'],'warning_title'=>'Varning','warning_desc'=>'Falsk information eller försök att lura staff kan leda till avslag och ytterligare straff.','form_not_available'=>'Direkt inskickning av överklaganden är inte tillgänglig just nu. Använd en kontaktmetod ovan.']
];