<?php
return [
 'site'=>['name'=>'Realms Bans','title'=>'{page} - Realms Bans','description'=>'Lịch sử xử phạt Minecraft công khai và có thể tìm kiếm của RealmsNetwork'],
 'nav'=>['home'=>'Trang chủ','bans'=>'Ban','mutes'=>'Mute','warnings'=>'Cảnh cáo','kicks'=>'Kick','statistics'=>'Thống kê','language'=>'Ngôn ngữ','theme'=>'Giao diện','admin'=>'Quản trị','protest'=>'Khiếu nại ban'],
 'home'=>['welcome'=>'Lịch sử xử phạt máy chủ','description'=>'Tìm người chơi và xem hoạt động kiểm duyệt gần đây','recent_activity'=>'Hoạt động gần đây','recent_bans'=>'Ban gần đây','recent_mutes'=>'Mute gần đây','no_recent_bans'=>'Không có ban gần đây','no_recent_mutes'=>'Không có mute gần đây','view_all_bans'=>'Xem tất cả ban','view_all_mutes'=>'Xem tất cả mute'],
 'search'=>['title'=>'Tìm người chơi','placeholder'=>'Nhập tên người chơi hoặc UUID...','help'=>'Bạn có thể tìm bằng tên người chơi hoặc UUID đầy đủ','button'=>'Tìm kiếm','no_results'=>'Không tìm thấy hình phạt cho người chơi này','error'=>'Đã xảy ra lỗi tìm kiếm','network_error'=>'Lỗi mạng. Vui lòng thử lại.'],
 'stats'=>['title'=>'Thống kê máy chủ','active_bans'=>'Ban đang hoạt động','active_mutes'=>'Mute đang hoạt động','total_warnings'=>'Tổng cảnh cáo','total_kicks'=>'Tổng kick','total_of'=>'trong tổng số','all_time'=>'mọi thời điểm','most_banned_players'=>'Người chơi bị ban nhiều nhất','most_active_staff'=>'Staff hoạt động nhiều nhất','top_ban_reasons'=>'Lý do ban phổ biến nhất','recent_activity_overview'=>'Tổng quan hoạt động gần đây','activity_by_day'=>'Hoạt động theo ngày','cache_cleared'=>'Đã xóa bộ nhớ đệm thống kê','cache_clear_failed'=>'Không thể xóa bộ nhớ đệm','clear_cache'=>'Xóa bộ nhớ đệm','last_24h'=>'24 giờ qua','last_7d'=>'7 ngày qua','last_30d'=>'30 ngày qua'],
 'table'=>['player'=>'Người chơi','reason'=>'Lý do','staff'=>'Staff','date'=>'Ngày','expires'=>'Hết hạn','status'=>'Trạng thái','actions'=>'Thao tác','type'=>'Loại','view'=>'Xem','total'=>'Tổng','active'=>'Hoạt động','last_ban'=>'Ban gần nhất','last_action'=>'Thao tác gần nhất','server'=>'Máy chủ'],
 'status'=>['active'=>'Đang hoạt động','inactive'=>'Không hoạt động','expired'=>'Đã hết hạn','removed'=>'Đã gỡ','completed'=>'Hoàn tất','removed_by'=>'Gỡ bởi'],
 'punishment'=>['permanent'=>'Vĩnh viễn','expired'=>'Đã hết hạn'],
 'punishments'=>['no_data'=>'Không tìm thấy hình phạt','no_data_desc'=>'Hiện không có hình phạt để hiển thị'],
 'detail'=>['duration'=>'Thời hạn','time_left'=>'Thời gian còn lại','progress'=>'Tiến độ','removed_by'=>'Gỡ bởi','removed_date'=>'Ngày gỡ','flags'=>'Cờ','other_punishments'=>'Hình phạt khác'],
 'pagination'=>['label'=>'Điều hướng trang','previous'=>'Trước','next'=>'Sau','page_info'=>'Trang {current} / {total}'],
 'footer'=>['rights'=>'Bảo lưu mọi quyền.','powered_by'=>'Được xây dựng bởi','license'=>'Cấp phép theo'],
 'error'=>['not_found'=>'Không tìm thấy trang','server_error'=>'Đã xảy ra lỗi máy chủ','invalid_request'=>'Yêu cầu không hợp lệ','punishment_not_found'=>'Không tìm thấy hình phạt được yêu cầu.','loading_failed'=>'Không thể tải chi tiết hình phạt.'],
 'protest'=>['title'=>'Khiếu nại ban','description'=>'Nếu bạn cho rằng mình bị ban nhầm, bạn có thể yêu cầu xem xét.','how_to_title'=>'Cách khiếu nại ban','how_to_subtitle'=>'Làm theo các bước sau để yêu cầu unban:','step1_title'=>'1. Chuẩn bị thông tin','step1_desc'=>'Hãy chuẩn bị:','step1_items'=>['Tên Minecraft','Ngày và giờ bị ban','Lý do ban','Bằng chứng hỗ trợ'],'step2_title'=>'2. Phương thức liên hệ','step2_desc'=>'Bạn có thể gửi khiếu nại bằng một trong các cách sau:','discord_title'=>'Discord (khuyến nghị)','discord_desc'=>'Tham gia Discord và tạo ticket trong khu vực khiếu nại ban','discord_button'=>'Mở Discord','email_title'=>'Email','email_desc'=>'Gửi khiếu nại tới:','forum_title'=>'Diễn đàn','forum_desc'=>'Tạo bài viết trong khu vực khiếu nại của diễn đàn.','forum_button'=>'Mở diễn đàn','step3_title'=>'3. Nội dung cần có','step3_desc'=>'Nêu tên, chuyện gì đã xảy ra, lý do khiếu nại và điều bạn muốn thay đổi.','step3_items'=>['Tên Minecraft','Ngày và thời gian gần đúng','Staff đã ban bạn nếu biết','Giải thích chi tiết','Ảnh chụp hoặc bằng chứng','Mô tả trung thực'],'step4_title'=>'4. Chờ xem xét','step4_desc'=>'Đội ngũ staff sẽ xem xét. Không gửi nhiều khiếu nại cho cùng một ban.','guidelines_title'=>'Hướng dẫn quan trọng','guidelines_items'=>['Hãy trung thực và tôn trọng','Không cung cấp thông tin sai','Không spam','Tôn trọng quyết định cuối cùng','Lách ban có thể dẫn đến ban vĩnh viễn'],'warning_title'=>'Cảnh báo','warning_desc'=>'Thông tin giả hoặc hành vi đánh lừa staff có thể khiến khiếu nại bị từ chối và bị phạt thêm.','form_not_available'=>'Hiện không hỗ trợ gửi khiếu nại trực tiếp. Vui lòng dùng một phương thức liên hệ ở trên.']
];